### ISSUE TITLE
decimals are not shown in excel

### ISSUE THREAD

**Issue by ThomasKnecht** [statistikZH/statR#20]
When I create an excel with the splitXLSX function, one column should have decimals but they are not shown.

The cell format in the excel is the following: ##'##0 even though in the function the cell format is set as: #,###0

statR-Version: 1.0.0.9999
R-Version: 4.0.4

**Comment by tlorusso** [comment]
I've now removed the global formatting option ##'##0 (dev branch), which was a bad idea in the first place. 

I suggest adding examples of how individual formatting of the columns is possible to the documentation. Or would you prefer adding an argument to the function that allows handling column formats? @ThomasKnecht 

This works:
```
class(mtcars$mpg) <- "currency"
class(mtcars$cyl) <- "accounting"
class(mtcars$qsec) <- "hyperlink"
class(mtcars$am) <- "percentage"
class(mtcars$vs) <- "scientific"

quickXLSX(mtcars, "mtcars",metadata=c("1","2"))
```
