### ISSUE TITLE
Team in Excel-Header (Kontaktdaten) - mehrere Optionen bieten

### ISSUE THREAD

**Issue by tlorusso** [statistikZH/statR#23]
Neben dem Datashop mehre Kontakte hinterlegen und zur Auswahl anbieten.

- Analyse 
- Wahlen & Abstimmungen
- Benchmarking

**Comment by Thomas-Caspar-Fischer** [comment]
In Arbeit für die kommende Version. Implementierung in Form von User Konfigurationen, die im extdata Ordner abgelegt werden und beim Laden von statR eingelesen werden.

Edit: User können nun mit der Funktion writeUserConfig Konfigurationen anlegen und diese mit der Funktion readUserConfig laden. Zur Vorgehensweise bei der Erstellung einer Konfiguration gibt es in der Hilfe zur writeUserConfig Funktion ein Beispiel.
