### ISSUE TITLE
option to set formats columnwise (xlsx-functions)

### ISSUE THREAD

**Issue by tlorusso** [statistikZH/statR#3]
provide an option to set column - wise formats (decimals e.g.) in the xlsx-functions (via  `insert_worksheet`)

**Comment by tlorusso** [comment]
class(mtcars$mpg) <- "currency"
class(mtcars$cyl) <- "accounting"
class(mtcars$qsec) <- "hyperlink"
class(mtcars$am) <- "percentage"
class(mtcars$vs) <- "scientific"

quickXLSX(mtcars, "mtcars",metadata=c("1","2"))

**Comment by mdllz** [comment]
This seems to work! :) Can we close this issue?
