### ISSUE TITLE
theme_stat

### ISSUE THREAD

**Issue by schnllr** [statistikZH/statR#35]
wäre es möglich bei option axis.lines auch zwei inputs zu ermölgichen, also axis.lines für x UND y
axis.lines = c("x","y")

**Comment by schnllr** [comment]
haha.. gibts ja bereits, mit "both". top :)

**Comment by schnllr** [comment]
sorry, habe missverstanden was axis.lines macht, das macht ja wirklich die Achsenlinien. Ich wäre interessiert an einem Parameter, mit dem man die grid.lines steuern kann. die sind per default für x als element_blank() gesetzt. wäre da ein Parameter denkbar, der für x, y, oder both aktiviert werden könnte? sorry für die Konfusion!

**Comment by mdllz** [comment]
resolved in #37
