### ISSUE TITLE
datasetsXLSX: Hyperlinks on Index Page seem to be broken

### ISSUE THREAD

**Issue by ruizcrp** [statistikZH/statR#39]
Hi,
when using the datasetsXLSX function, the hyperlinks on the index page seem to be broken. They look like this: 

=HYPERLINK(&quot;#&apos;Alle Angebote&apos;!A1&quot;, &quot;Kostenübersicht aller Angebotsnutzungen für Gemeinde Dielsdorf&quot;)

![grafik](https://user-images.githubusercontent.com/12788884/142407546-a4093c9e-7d64-4302-aa23-65d8a8f877a1.png)

**Comment by ruizcrp** [comment]
![grafik](https://user-images.githubusercontent.com/12788884/142418017-0df6c813-c7c3-4d3e-99dd-072f51b8b7a8.png)

**Comment by ruizcrp** [comment]
When looking at wb-object
![grafik](https://user-images.githubusercontent.com/12788884/142419781-3a68a8e9-7c11-4576-bac3-505a8171c0bb.png)

**Comment by ruizcrp** [comment]
I Think there are two issues. 
1) The function openxlsx::makeHyperlinkString generates a HYPERLINK with a comma (as in ENglish Excel) as opposed to semicolon (as in German Excel) for the separation wthin a formula. 
2) However, the main issue seems to be the conversion of the string. It happens within openxlsx::writeFormula. I also tried to replace openxlsx::makeHyperlinkString with a manual string, but the encoding was the same.

**Comment by ThomasKnecht** [comment]
How should the string for the hyperlink look like in the end?

**Comment by ruizcrp** [comment]
I think the following is the closes to what we need:
=HYPERLINK("#'Alle Angebote'!A1", "Kostenübersicht aller Angebotsnutzungen für Gemeinde Dielsdorf")

However, not sure about the comma, as in the German Excel this would be a semicolon (however, maybe it is saved with a comma)

**Comment by ThomasKnecht** [comment]
the example seems to work

do you have a reprex where it does not work?

**Comment by Thomas-Caspar-Fischer** [comment]
Closing, as hyperlinks are currently working (based on makeHyperlinkString and writeFormula from the openxlsx package).
