### ISSUE TITLE
Change request: datasetsXLSX set source manually

### ISSUE THREAD

**Issue by ruizcrp** [statistikZH/statR#40]
parameter for datasetsXLSX like quelle_inhalt or so to change the standard value of
"Quelle: Statistisches Amt des Kantons Zürich" which appears at the inhalt-page

**Comment by ThomasKnecht** [comment]
This exists. The the parameter is called: sources. By default, "statzh" is set, which results in the above mentioned source definition. You can change that by passing a character vector to this parameter with your own source definition.

**Comment by Thomas-Caspar-Fischer** [comment]
I concur. Still, the coming version will rename the argument providing the source shown on the index sheet to make them more easily distinguishable.

Edit: as of version 2.3.1, the tile shown on the index sheet is set by the argument index_title, and the source by the argument index_source.
