### ISSUE TITLE
Einfügen von Plots in Excel Tabellen funkioniert nicht

### ISSUE THREAD

**Issue by alexandrawu** [statistikZH/statR#47]
```
Error in datasetsXLSX(file = "twoDatasetsandFigure", maintitle = "Autos und Pflanzen",  : 
  unused arguments (widths = c(0, 0, 5), heights = c(0, 0, 5), startrows = c(0, 0, 3), startcols = c(0, 0, 3))
```
https://statistikzh.github.io/statR/articles/Excel-Tabellen.html
Beispielcode für Excel Tabellen mit Grafiken funktioniert nicht.

**Comment by Thomas-Caspar-Fischer** [comment]
Problem war, dass im Beispielscode ein base histogram Objekt eingefügt wurde. Die Logik dafür war aber noch nicht implementiert. In der kommenden Version wird das Problem behoben.
