### ISSUE TITLE
Release Issue 

### ISSUE THREAD

**Issue by tlorusso** [statistikZH/statR#49]
- [x] Update documentation with recommendations for color palettes / build pkgdown site with `pkgdown::build_site()`
- [x] Check / test feature branch
- [x] Merge color palette feature branch into the dev branch
- [x] Check / test dev branch
- [x] Increment version `usethis::use_version()` 
- [x] Document changes `usethis::use_newsmd()` (change document manually is possible as well)
- [x] merge into master, if everything works well
- [x] Check / test master branch
- [x] Inform users regarding the update (slack)

**Comment by Thomas-Caspar-Fischer** [comment]
Release 2.3.1 is out
