### ISSUE TITLE
Package Version io-Page / Error quickXLSX

### ISSUE THREAD

**Issue by BasilSch** [statistikZH/statR#58]
Der Package version on https://statistikzh.github.io/statR/ is 2.2.0

![grafik](https://github.com/statistikZH/statR/assets/49457430/5e7038ee-b9c1-44c1-88ec-09ddb1feb750)

the following example from the io-Page does not run under the Version 2.3.2

```

dat <- mtcars

quickXLSX(data = dat, 
          title = "Motor trend car road tests", 
          file = "motor_trend_car_road_tests", # '.xlsx' wird automatisch hinzugefügt
          source = "Source: Henderson and Velleman (1981). Building multiple regression models interactively. Biometrics, 37, 391–411.",
          metadata = c("The data was extracted from the 1974 Motor Trend US magazine and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models)."),
          contactdetails = "statzh",
          logo = "statzh",
          grouplines = FALSE,
          author = "MD")
```

I get this error:

![grafik](https://github.com/statistikZH/statR/assets/49457430/7d6f6a2f-ae5f-4356-97cf-72fa75f1f646)

Session Info:

![grafik](https://github.com/statistikZH/statR/assets/49457430/aec3de65-b04f-4790-b79a-e0b5af380364)

**Comment by Thomas-Caspar-Fischer** [comment]
The documentation needed to be brought up to date (Version 2.4.1).
