### ISSUE TITLE
Metadata on multiple lines (splitxlsx; quickxlsx)

### ISSUE THREAD

**Issue by ThomasKnecht** [statistikZH/statR#6]
It would be nice to to have multiple cells for the metadata. (e.g. 2), so that not everything is written behind each other in a single line.

**Comment by kalakaru** [comment]
I agree, it would be nice if by default the following metadata could be added: 

- [ ] Quelle
- [ ] Gebiet
- [ ]  Zeitraum
- [ ] Hinweis.

**Comment by tlorusso** [comment]
this is already possible by passing a vector with multiple elements to the `metadata`-argument. 

`quickXLSX(mtcars, "mtcars", metadata=c("Quelle: BFS", "Gebiet: Zürich")) `
