### ISSUE TITLE
theme_stat anpassen

### ISSUE THREAD

**Issue by schnllr** [statistikZH/statR#9]
angleichen an theme_stat2()
L:\STAT\03_AS\01_Werkzeuge\01_Toolbox\R\Funktionen\theme_stat2

- flexibles Handling von Schrift und Schriftgrössen

**Comment by tlorusso** [comment]
Zwei Optionen anbieten : 

- Plot mit kategorialen und kontinuierlichen Skalen (existiert bereits)
- Plot mit kontiniuerlichen x / y - Achsen

**Comment by mdllz** [comment]
theme_stat() ist an theme_stat2() angeglichen und die Schriftgrösse, Achsenlinien, Ticks, Gitterlinien und Positionen der Achsenbeschriftungen können angepasst bzw. hinzugefügt/entfernt werden.
